@URL = http://localhost:3000

POST {{URL}}/auth/signup
Accept: application/json
Content-Type: application/json

{
    "username": "User01",
    "password": "12345678",
    "confirmPassword": "12345678"
}

###

POST {{URL}}/auth/login
Accept: application/json
Content-Type: application/json

{
    "username": "User01",
    "password": "12345678"
}

###

GET {{URL}}/auth/travel
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlVzZXIwMSIsImlhdCI6MTcyNzAzODYzMywiZXhwIjoxNzI3MDQyMjMzfQ.wIjLneoUN11fSJC8P3_GoMewWSt_dzf-eOPEWlXyKRc

###

POST {{URL}}/auth/travel
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlVzZXIwMSIsImlhdCI6MTcyNzAzODYzMywiZXhwIjoxNzI3MDQyMjMzfQ.wIjLneoUN11fSJC8P3_GoMewWSt_dzf-eOPEWlXyKRc

{
    "description": "Test travel",
    "plannedStartDate": "2024-09-22T14:30:00-0500",
    "plannedEndDate": "2024-09-22T13:52:00-0500"
}
